# Generated by Django 6.1.1 on 2026-09-24 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_backer_reward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='originating_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_orders', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='order',
            name='originating_pledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_orders', to='campaigns.pledge'),
        ),
    ]
