# Generated by Django 6.1.1 on 2026-09-18 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='Home & Living', max_length=255)),
                ('craft_heritage_note', models.CharField(default='Traditional Craft', max_length=255)),
                ('region_state', models.CharField(default='India', max_length=255)),
                ('in_stock', models.BooleanField(default=True)),
                ('stock_quantity', models.IntegerField(default=10)),
                ('is_funded_on_platform', models.BooleanField(default=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=4.9, max_digits=3)),
                ('reviews_count', models.IntegerField(default=12)),
                ('image', models.CharField(default='/images/products/jaipur-blue-pottery-tea-set.jpg', max_length=500)),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduated_products', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Conscious Buyer', max_length=255)),
                ('rating', models.IntegerField(default=5)),
                ('title', models.CharField(default='Exceptional Quality', max_length=255)),
                ('comment', models.TextField()),
                ('verified_buyer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
