# Generated by Django 6.1.1 on 2026-09-18 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('craft_type', models.CharField(default='Traditional Craft', max_length=255)),
                ('region_state', models.CharField(default='India', max_length=255)),
                ('description', models.TextField()),
                ('funding_goal', models.DecimalField(decimal_places=2, default=100000.0, max_digits=12)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('backers_count', models.IntegerField(default=0)),
                ('days_left', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('funded', 'Funded'), ('failed', 'Failed'), ('pending_review', 'Pending Review'), ('rejected', 'Rejected')], default='in_progress', max_length=30)),
                ('image', models.CharField(default='/images/products/jaipur-blue-pottery-tea-set.jpg', max_length=500)),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('is_approved', models.BooleanField(default=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_title', models.CharField(default='Heritage Patron Supporter', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('authorized', 'Authorized (Pre-auth Escrow)'), ('authorized_pending', 'Authorized Pending'), ('captured', 'Captured (Goal Met)'), ('released', 'Released (Goal Failed)'), ('cancelled', 'Cancelled')], default='authorized', max_length=30)),
                ('backer_name', models.CharField(default='Conscious Patron', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_delivery', models.CharField(default='Dec 2026', max_length=100)),
                ('settlement_date', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='campaigns.campaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProofSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.CharField(blank=True, max_length=500, null=True)),
                ('gps_latitude', models.FloatField(blank=True, null=True)),
                ('gps_longitude', models.FloatField(blank=True, null=True)),
                ('has_exif_gps', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_submissions', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='RewardTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=1200.0, max_digits=10)),
                ('description', models.TextField()),
                ('estimated_delivery', models.CharField(default='Nov 2026', max_length=100)),
                ('items_included', models.JSONField(blank=True, default=list)),
                ('backers_count', models.IntegerField(default=0)),
                ('max_backers', models.IntegerField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_tiers', to='campaigns.campaign')),
            ],
        ),
    ]
