const fs = require('fs');
const path = require('path');

const mockDataContent = `import { Campaign, Product, User, UserPledgeRecord, BackerRecord, CampaignUpdate, CampaignComment, RewardTier } from '../types';
import { EXACT_PRODUCT_IMAGES } from './artisanAssets';

export const INITIAL_USER: User = {
  id: 'usr-001',
  name: 'Aarav Sharma',
  email: 'aarav.sharma@indiamail.in',
  role: 'backer',
  avatarInitials: 'AS',
  memberSince: 'March 2025',
  shippingAddress: {
    street: '42, 3rd Cross, Indiranagar',
    city: 'Bengaluru',
    state: 'Karnataka',
    zip: '560038',
    country: 'India',
  },
};

export const INITIAL_USER_PLEDGES: UserPledgeRecord[] = [
  {
    id: 'pld-001',
    buyerId: 'usr-001',
    campaignId: 'cmp-01',
    campaignTitle: 'Revive Chanderi Pit-Loom Weaving — New Looms & Natural Indigo Dye Setup',
    campaignCode: 'CMP-101',
    tierTitle: 'Pure Chanderi Cotton-Silk Scarf with Zari Border',
    amount: 2499,
    dateAuthorized: 'Sep 02, 2026',
    status: 'authorized',
    estimatedDelivery: 'Nov 2026',
  },
  {
    id: 'pld-002',
    buyerId: 'usr-001',
    campaignId: 'cmp-02',
    campaignTitle: 'Jaipur Blue Pottery Studio Expansion & Lead-Free Solar Kiln',
    campaignCode: 'CMP-102',
    tierTitle: 'Set of 2 Cobalt Blue Glazed Decorative Platters',
    amount: 1499,
    dateAuthorized: 'Sep 08, 2026',
    status: 'authorized',
    estimatedDelivery: 'Dec 2026',
  },
  {
    id: 'pld-003',
    buyerId: 'usr-001',
    campaignId: 'cmp-03',
    campaignTitle: 'Sustainable Assam Bhaluka Bamboo & Cane Workshop Setup',
    campaignCode: 'CMP-103',
    tierTitle: 'Woven Bamboo Desk Organizer & Pen Stand',
    amount: 799,
    dateAuthorized: 'Sep 05, 2026',
    status: 'authorized',
    estimatedDelivery: 'Oct 2026',
  },
  {
    id: 'pld-004',
    buyerId: 'usr-001',
    campaignId: 'cmp-05',
    campaignTitle: 'Kutch Rogan Castor-Oil Fabric Painting Preservation Guild',
    campaignCode: 'CMP-105',
    tierTitle: 'Hand-painted Rogan Silk Bookmark & Pouch',
    amount: 650,
    dateAuthorized: 'Sep 01, 2026',
    status: 'authorized',
    estimatedDelivery: 'Nov 2026',
  },
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'cmp-01',
    code: 'CMP-101',
    title: 'Revive Chanderi Pit-Loom Weaving — New Looms & Natural Indigo Dye Setup',
    creator: 'Radha Devi, Chanderi, Madhya Pradesh — 3rd Generation Weaver',
    creatorBio: 'Third-generation master weaver from the historic town of Chanderi, leading an all-women artisan cooperative dedicated to unadulterated pit-loom weaving.',
    creatorLocation: 'Chanderi, Madhya Pradesh',
    artisanRegion: 'Chanderi, Madhya Pradesh',
    craftHeritage: 'GI-Tagged Chanderi Handloom Weaving',
    category: 'Textiles & Weaving',
    shortDescription: 'Empowering 12 rural women weavers with heavy teakwood pit-looms, zero-chemical natural indigo vats, and direct patron-to-loom pre-orders.',
    fullStory: "For over six centuries, the weavers of Chanderi in Madhya Pradesh have hand-spun airy gossamer fabrics prized by royal courts. Today, synthetic power-loom imitations threaten our sacred pit-loom heritage. Through this campaign on Craftify, our self-help artisan collective aims to install 4 heavy Burma-teak pit-looms and establish a chemical-free organic dye facility using pomegranate rinds, madder root, and forest indigo. By backing this initiative, you bypass multiple tiers of wholesale dealers, ensuring 92% of all pledged funds go straight to weaver wages and mulberry silk raw materials.",
    goalAmount: 250000,
    fundingGoal: 250000,
    pledgedAmount: 315000,
    amountRaised: 315000,
    backersCount: 340,
    daysLeft: 14,
    deadline: '2026-10-15',
    status: 'in_progress',
    isApproved: true,
    creatorProfilePhoto: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    creatorBusinessName: 'Radha Devi Handloom Collective',
    creatorYearsOfExperience: 24,
    creatorCity: 'Chanderi',
    creatorState: 'Madhya Pradesh',
    creatorLegalName: 'Radha Devi Sharma',
    creatorPhone: '+91 98261 44520',
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80&sig=101',
    specs: [
      { label: 'Craft Origin', value: 'Chanderi, Ashoknagar District, Madhya Pradesh (GI-Tagged)' },
      { label: 'Yarn Blend', value: '70% Fine Handspun Cotton & 30% Pure Mulberry Silk' },
      { label: 'Zari Material', value: 'Tested Silver-Plated Copper Thread (Tested Zari)' },
      { label: 'Dye Process', value: '100% Plant-Based Indigo, Madder & Pomegranate' },
      { label: 'Loom Type', value: 'Traditional Wooden Pit-Loom with Jacquard Dobby' },
    ],
    timeline: [
      { phase: 'Raw Silk & Timber Procurement', date: 'August 2026', description: 'Procured seasoned teakwood timber and certified mulberry warp silk.' },
      { phase: 'Crowdfunding Phase', date: 'Sept 2026', description: 'Conditional escrow authorization on Craftify.' },
      { phase: 'Pit-Loom Installation & Warping', date: 'Oct 2026', description: 'Erecting 4 new looms and stringing 10,000 warp ends.' },
      { phase: 'Weaving & Backer Dispatch', date: 'Nov 2026', description: 'Hand-weaving backer scarves and sarees with artisan tag.' },
    ],
    rewardTiers: [
      {
        id: 'tier-01-a',
        title: 'Natural Indigo Silk Pocket Squares (Set of 2)',
        pledgeAmount: 999,
        description: 'Set of two gossamer cotton-silk pocket squares hand-dyed in organic forest indigo with hand-rolled hems.',
        estimatedDelivery: 'Oct 2026',
        itemsIncluded: ['2x Hand-dyed Chanderi Silk Pocket Squares', 'Artisan Story Card signed by Radha Devi'],
        backersCount: 92,
        maxBackers: 100,
      },
      {
        id: 'tier-01-b',
        title: 'Pure Chanderi Cotton-Silk Scarf with Zari Border',
        pledgeAmount: 2499,
        description: 'Handwoven 2-meter stoles featuring traditional Ashrafi butis and intricate gold-toned zari edging.',
        estimatedDelivery: 'Nov 2026',
        itemsIncluded: ['1x Handwoven Chanderi Scarf (200cm × 65cm)', 'Silk Mark & GI Authentication Certificate'],
        backersCount: 198,
        maxBackers: 250,
      },
    ],
  },
  {
    id: 'cmp-02',
    code: 'CMP-102',
    title: 'Jaipur Blue Pottery Studio Expansion & Lead-Free Solar Kiln',
    creator: 'Rameshwar Prajapati, Jaipur, Rajasthan — Master Potter',
    creatorBio: 'National award-winning potter from Kot Jewar near Jaipur, preserving the rare lead-free Egyptian paste technique.',
    creatorLocation: 'Jaipur, Rajasthan',
    artisanRegion: 'Jaipur, Rajasthan',
    craftHeritage: 'GI-Tagged Jaipur Blue Pottery',
    category: 'Pottery & Ceramics',
    shortDescription: 'Constructing energy-efficient gas kilns to train 18 youth artisans and create lead-free, food-safe cobalt tableware.',
    fullStory: "Jaipur Blue Pottery is hand-molded from a rare dough of quartz stone powder, Fuller's earth, powdered glass, and gum. It is glazed once at 800°C with mineral pigments of cobalt oxide. Our current wood-fired kiln produces uneven heating, causing thermal cracking. With this Craftify campaign, we are constructing a precision digital gas kiln and setting up a dedicated training workshop for 18 young village potters.",
    goalAmount: 200000,
    fundingGoal: 200000,
    pledgedAmount: 170000,
    amountRaised: 170000,
    backersCount: 195,
    daysLeft: 12,
    deadline: '2026-10-20',
    status: 'in_progress',
    isApproved: true,
    creatorProfilePhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    creatorBusinessName: 'Prajapati Blue Pottery Studio',
    creatorYearsOfExperience: 32,
    creatorCity: 'Jaipur',
    creatorState: 'Rajasthan',
    creatorLegalName: 'Rameshwar Prajapati',
    creatorPhone: '+91 98290 12345',
    imageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80&sig=102',
    specs: [
      { label: 'Craft Origin', value: 'Kot Jewar, Jaipur, Rajasthan (GI Tagged)' },
      { label: 'Raw Materials', value: 'Quartz Powder, Multani Mitti, Katira Gond & Glass' },
      { label: 'Glaze Chemistry', value: '100% Lead-Free Cobalt Pigments' },
    ],
    timeline: [
      { phase: 'Kiln Site Layout & Blueprints', date: 'August 2026', description: 'Thermal blueprints finalized.' },
      { phase: 'Kiln Assembly', date: 'Oct 2026', description: 'Setting up refractories and cobalt glaze batches.' },
    ],
    rewardTiers: [
      {
        id: 'tier-02-a',
        title: 'Hand-Painted Blue Pottery Coasters & Incense Holder',
        pledgeAmount: 599,
        description: 'Set of 4 hand-painted quartz pottery coasters with cork base in signature Persian blue.',
        estimatedDelivery: 'Nov 2026',
        itemsIncluded: ['4x Floral Blue Pottery Coasters', '1x Incense Burner'],
        backersCount: 88,
        maxBackers: 120,
      },
      {
        id: 'tier-02-b',
        title: 'Set of 2 Cobalt Blue Glazed Decorative Platters',
        pledgeAmount: 1499,
        description: 'Pair of 8-inch hand-painted dessert platters with traditional Mughal floral arabesque motifs.',
        estimatedDelivery: 'Dec 2026',
        itemsIncluded: ['2x 8-inch Decorative Wall Platters', '2x Wall Brackets'],
        backersCount: 85,
        maxBackers: 150,
      },
    ],
  },
  {
    id: 'cmp-03',
    code: 'CMP-103',
    title: 'Sustainable Assam Bhaluka Bamboo & Cane Workshop Setup',
    creator: 'Bhaskar Sharma, Barpeta, Assam — Master Bamboo Artisan',
    creatorBio: 'Practicing bamboo craftsman carrying forward generational knowledge of indigenous splinting and non-toxic boiling treatments.',
    creatorLocation: 'Barpeta, Assam',
    artisanRegion: 'Barpeta, Assam',
    craftHeritage: 'Assam Sustainable Bamboo & Cane Craft',
    category: 'Wood & Bamboo',
    shortDescription: 'Modernizing a village bamboo treatment kiln in Barpeta to transform sustainable Bhaluka bamboo into heirloom living furniture.',
    fullStory: "Assam is blessed with native Bhaluka bamboo possessing the tensile strength of mild steel. Our collective is building a solar-heated non-toxic borax treatment plant to render bamboo immune to boring beetles for 25+ years.",
    goalAmount: 320000,
    fundingGoal: 320000,
    pledgedAmount: 385000,
    amountRaised: 385000,
    backersCount: 245,
    daysLeft: 0,
    deadline: '2026-09-15',
    status: 'in_progress',
    isApproved: true,
    creatorProfilePhoto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=400',
    creatorBusinessName: 'Barpeta Bamboo & Cane Guild',
    creatorYearsOfExperience: 19,
    creatorCity: 'Barpeta',
    creatorState: 'Assam',
    creatorLegalName: 'Bhaskar Sharma',
    creatorPhone: '+91 94350 23456',
    imageUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80&sig=103',
    specs: [
      { label: 'Craft Origin', value: 'Barpeta & Nalbari, Assam' },
      { label: 'Species', value: 'Bambusa balcooa (Assamese Bhaluka Bamboo)' },
    ],
    timeline: [
      { phase: 'Treatment Tank Sourcing', date: 'July 2026', description: 'Designed solar immersion vessel.' },
      { phase: 'Harvesting Bamboo', date: 'Oct 2026', description: 'Harvesting winter bamboo during low-sap season.' },
    ],
    rewardTiers: [
      {
        id: 'tier-03-a',
        title: 'Woven Bamboo Desk Organizer & Pen Stand',
        pledgeAmount: 799,
        description: 'Multi-compartment desk organizer meticulously woven from fine bamboo Trat strips.',
        estimatedDelivery: 'Oct 2026',
        itemsIncluded: ['1x Woven Bamboo Desk Organizer', '1x Bamboo Pen'],
        backersCount: 110,
        maxBackers: 150,
      },
    ],
  },
  {
    id: 'cmp-04',
    code: 'CMP-104',
    title: 'Madhubani Folk Painting Collective — Natural Pigment & Raw Silk Guild',
    creator: 'Sita Devi Karn, Jitwarpur, Bihar — Mithila Master Painter',
    creatorBio: 'National award winner dedicated to empowering Mithila women through natural mineral dye painting on handmade silk parchment.',
    creatorLocation: 'Jitwarpur, Madhubani, Bihar',
    artisanRegion: 'Madhubani, Bihar',
    craftHeritage: 'GI-Tagged Madhubani Folk Art',
    category: 'Folk & Tribal Art',
    shortDescription: 'Funding raw tussar silk scrolls, natural plant dyes, and bamboo nibs for 20 Mithila women painters in Jitwarpur.',
    fullStory: "Madhubani painting uses twigs, nibs, and fingers to create intricate geometric patterns depicting nature and mythology. This campaign establishes a raw silk sourcing pool and organic pigment extraction center for rural women artists.",
    goalAmount: 180000,
    fundingGoal: 180000,
    pledgedAmount: 145000,
    amountRaised: 145000,
    backersCount: 168,
    daysLeft: 18,
    deadline: '2026-10-25',
    status: 'in_progress',
    isApproved: true,
    creatorProfilePhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    creatorBusinessName: 'Mithila Mahila Kalakriti Collective',
    creatorYearsOfExperience: 28,
    creatorCity: 'Madhubani',
    creatorState: 'Bihar',
    creatorLegalName: 'Sita Devi Karn',
    creatorPhone: '+91 94310 87654',
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80&sig=104',
    specs: [
      { label: 'Craft Origin', value: 'Jitwarpur, Madhubani, Bihar (GI Tagged)' },
      { label: 'Medium', value: 'Organic Indigo, Turmeric, Madder & Soot Pigments' },
    ],
    timeline: [
      { phase: 'Silk Sourcing & Sizing', date: 'August 2026', description: 'Procuring raw Bhagalpur tussar silk.' },
      { phase: 'Painting & Backer Dispatch', date: 'Nov 2026', description: 'Painting commissioned artworks.' },
    ],
    rewardTiers: [
      {
        id: 'tier-04-a',
        title: 'Hand-Painted Madhubani Silk Bookmark & Postcard',
        pledgeAmount: 499,
        description: 'Authentic miniature painting on handmade paper with natural dyes.',
        estimatedDelivery: 'Oct 2026',
        itemsIncluded: ['1x Hand-painted Bookmark', '1x Story Card'],
        backersCount: 75,
        maxBackers: 100,
      },
    ],
  },
  {
    id: 'cmp-05',
    code: 'CMP-105',
    title: 'Kutch Rogan Castor-Oil Fabric Painting Preservation Guild',
    creator: 'Rizwan Khatri, Nirona, Gujarat — Master Rogan Artisan',
    creatorBio: 'Preserving the rare 400-year-old Persian Rogan painting on wild tussar silk using boiled castor oil paste and natural mineral earths.',
    creatorLocation: 'Nirona, Kutch, Gujarat',
    artisanRegion: 'Nirona, Kutch, Gujarat',
    craftHeritage: 'GI-Tagged Rogan Art of Kutch',
    category: 'Textiles & Weaving',
    shortDescription: 'Establishing communal castor-oil heating vats and iron stylus toolkits for 8 apprentice artisans in Nirona.',
    fullStory: "Rogan painting is an endangered craft. Heated castor oil is mixed with stone pigments to create a sticky paste, drawn into fine threads using a metal needle to paint freehand on fabric.",
    goalAmount: 200000,
    fundingGoal: 200000,
    pledgedAmount: 135000,
    amountRaised: 135000,
    backersCount: 112,
    daysLeft: 10,
    deadline: '2026-10-18',
    status: 'in_progress',
    isApproved: true,
    creatorProfilePhoto: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=400',
    creatorBusinessName: 'Nirona Rogan Art Heritage',
    creatorYearsOfExperience: 22,
    creatorCity: 'Nirona, Kutch',
    creatorState: 'Gujarat',
    creatorLegalName: 'Rizwan Khatri',
    creatorPhone: '+91 98250 34567',
    imageUrl: 'https://images.unsplash.com/photo-1606744888344-493238951221?auto=format&fit=crop&w=800&q=80&sig=105',
    specs: [
      { label: 'Craft Origin', value: 'Nirona, Kutch, Gujarat (GI Tagged)' },
      { label: 'Pigment Medium', value: 'Boiled Castor Seed Oil Gel (Rogan Paste)' },
    ],
    timeline: [
      { phase: 'Castor Gel Preparation', date: 'August 2026', description: 'Boiling castor oil paste.' },
      { phase: 'Apprentice Training', date: 'Nov 2026', description: 'Training new village artisans.' },
    ],
    rewardTiers: [
      {
        id: 'tier-05-a',
        title: 'Hand-painted Rogan Silk Bookmark & Pouch',
        pledgeAmount: 650,
        description: 'Silk bookmark with traditional Tree of Life motif hand-drawn with castor oil paste.',
        estimatedDelivery: 'Nov 2026',
        itemsIncluded: ['1x Hand-painted Silk Bookmark', '1x Bio Booklet'],
        backersCount: 50,
        maxBackers: 100,
      },
    ],
  },
  {
    id: 'cmp-06',
    code: 'CMP-106',
    title: 'Swamimalai Bronze & Brass Lost-Wax Casting Workshop Upgrade',
    creator: 'Devendra Sthapathy, Swamimalai, Tamil Nadu — Bronze Sculptor',
    creatorBio: 'Hereditary Chola bronze sculptor continuing the 1000-year lost-wax casting traditions of Swamimalai.',
    creatorLocation: 'Swamimalai, Thanjavur, Tamil Nadu',
    artisanRegion: 'Swamimalai, Tamil Nadu',
    craftHeritage: 'GI-Tagged Swamimalai Bronze Icons',
    category: 'Jewellery & Metalwork',
    shortDescription: 'Upgrading traditional charcoal smelting hearths and clay-slurry vats for 15 lost-wax metalsmiths in Swamimalai.',
    fullStory: "Lost-wax casting (cire perdue) involves hand-sculpting wax icons, coating them in Cauvery river clay, melting the wax, and pouring molten bronze. This project builds safer, low-smoke furnaces for our sculptors guild.",
    goalAmount: 280000,
    fundingGoal: 280000,
    pledgedAmount: 240000,
    amountRaised: 240000,
    backersCount: 210,
    daysLeft: 15,
    deadline: '2026-10-22',
    status: 'in_progress',
    isApproved: true,
    creatorProfilePhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    creatorBusinessName: 'Swamimalai Chola Bronze Guild',
    creatorYearsOfExperience: 31,
    creatorCity: 'Swamimalai',
    creatorState: 'Tamil Nadu',
    creatorLegalName: 'Devendra Sthapathy',
    creatorPhone: '+91 94430 76543',
    imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80&sig=106',
    specs: [
      { label: 'Craft Origin', value: 'Swamimalai, Thanjavur, Tamil Nadu (GI Tagged)' },
      { label: 'Alloy', value: 'Pancha-Loka (5-Metal Bronze Alloy)' },
    ],
    timeline: [
      { phase: 'Furnace Construction', date: 'Sept 2026', description: 'Erecting clean combustion hearths.' },
      { phase: 'Casting & Polishing', date: 'Nov 2026', description: 'Casting patron icons.' },
    ],
    rewardTiers: [
      {
        id: 'tier-06-a',
        title: 'Hand-Cast Brass Diya Lamp with Peacock Finial',
        pledgeAmount: 1199,
        description: 'Authentic lost-wax brass oil lamp handcrafted by Swamimalai sculptors.',
        estimatedDelivery: 'Nov 2026',
        itemsIncluded: ['1x Hand-cast Brass Diya', 'GI Certificate'],
        backersCount: 65,
        maxBackers: 100,
      },
    ],
  },
  {
    id: 'cmp-07',
    code: 'CMP-107',
    title: 'Saharanpur Sheesham Wood Carving Studio Solarization & Seasoning Unit',
    creator: 'Kishore Bhatt, Saharanpur, UP — Master Woodcarver',
    creatorBio: 'Master artisan creating lattice jali screens and inlaid furniture from kiln-dried Indian rosewood.',
    creatorLocation: 'Saharanpur, Uttar Pradesh',
    artisanRegion: 'Saharanpur, Uttar Pradesh',
    craftHeritage: 'GI-Tagged Saharanpur Wood Craft',
    category: 'Woodcraft',
    shortDescription: 'Installing solar kiln seasoning chambers to prevent wood warping and support 25 woodcarvers in Saharanpur.',
    fullStory: "Unseasoned wood cracks over time. By establishing a solar timber drying kiln, our artisan collective ensures that every carved panel and box retains structural perfection for decades.",
    goalAmount: 220000,
    fundingGoal: 220000,
    pledgedAmount: 195000,
    amountRaised: 195000,
    backersCount: 182,
    daysLeft: 8,
    deadline: '2026-10-12',
    status: 'in_progress',
    isApproved: true,
    creatorProfilePhoto: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=400',
    creatorBusinessName: 'Saharanpur Wooden Heritage Collective',
    creatorYearsOfExperience: 25,
    creatorCity: 'Saharanpur',
    creatorState: 'Uttar Pradesh',
    creatorLegalName: 'Kishore Bhatt',
    creatorPhone: '+91 98370 54321',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80&sig=107',
    specs: [
      { label: 'Craft Origin', value: 'Saharanpur, UP (GI Tagged)' },
      { label: 'Timber Species', value: 'Kiln-Dried Sheesham & Teakwood' },
    ],
    timeline: [
      { phase: 'Solar Kiln Setup', date: 'August 2026', description: 'Installing solar thermal panels.' },
      { phase: 'Carving Production', date: 'Oct 2026', description: 'Carving backer panels.' },
    ],
    rewardTiers: [
      {
        id: 'tier-07-a',
        title: 'Hand-Carved Sheesham Coaster Box Set',
        pledgeAmount: 750,
        description: 'Set of 6 floral carved coasters in a solid wood holder.',
        estimatedDelivery: 'Nov 2026',
        itemsIncluded: ['6x Carved Coasters', '1x Carved Storage Box'],
        backersCount: 60,
        maxBackers: 100,
      },
    ],
  },
  {
    id: 'cmp-08',
    code: 'CMP-108',
    title: 'Kolhapuri Vegetable-Tanned Leather Footwear Guild Expansion',
    creator: 'Harishankar Verma, Jodhpur & Kolhapur — Royal Mojari Artisan',
    creatorBio: 'Leading a guild of rural leather craftsmen using bark-tanned supple leather for durable, ergonomic sandals.',
    creatorLocation: 'Kolhapur, Maharashtra',
    artisanRegion: 'Kolhapur, Maharashtra',
    craftHeritage: 'GI-Tagged Kolhapuri Chappals & Leatherwork',
    category: 'Leather Craft',
    shortDescription: 'Setting up eco-friendly babool-bark tanning pits and ergonomic stitching stations for 30 cobblers in Athani & Kolhapur.',
    fullStory: "Authentic Kolhapuri footwear uses vegetable tanning with local Myrobalan and Babool bark. This campaign builds zero-chemical tanning pits and ergonomic lasting benches for rural cobblers.",
    goalAmount: 240000,
    fundingGoal: 240000,
    pledgedAmount: 185000,
    amountRaised: 185000,
    backersCount: 160,
    daysLeft: 11,
    deadline: '2026-10-16',
    status: 'in_progress',
    isApproved: true,
    creatorProfilePhoto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    creatorBusinessName: 'Kolhapur Leather Cobblers Guild',
    creatorYearsOfExperience: 27,
    creatorCity: 'Kolhapur',
    creatorState: 'Maharashtra',
    creatorLegalName: 'Harishankar Verma',
    creatorPhone: '+91 98220 12345',
    imageUrl: 'https://images.unsplash.com/photo-1560343090-f0409e92791a?auto=format&fit=crop&w=800&q=80&sig=108',
    specs: [
      { label: 'Craft Origin', value: 'Kolhapur, MH & Athani, KA (GI Tagged)' },
      { label: 'Tanning', value: '100% Babool Bark Vegetable Tanned' },
    ],
    timeline: [
      { phase: 'Tanning Pit Construction', date: 'Sept 2026', description: 'Excavating eco pits.' },
      { phase: 'Stitching & Lasting', date: 'Nov 2026', description: 'Hand-stitching backer orders.' },
    ],
    rewardTiers: [
      {
        id: 'tier-08-a',
        title: 'Hand-Stitched Leather Keychain & Card Sleeve',
        pledgeAmount: 450,
        description: 'Vegetable-tanned leather card wallet with brass keyring.',
        estimatedDelivery: 'Oct 2026',
        itemsIncluded: ['1x Leather Card Sleeve', '1x Key Ring'],
        backersCount: 80,
        maxBackers: 120,
      },
    ],
  },
  {
    id: 'cmp-09',
    code: 'CMP-109',
    title: 'Kashmir Pashmina Hand-Spinning & Wooden Loom Preservation Project',
    creator: 'Ghulam Hassan, Srinagar, Kashmir — Master Pashmina Weaver',
    creatorBio: 'Preserving authentic hand-spun Changthangi cashmere handloom weaving in Srinagar.',
    creatorLocation: 'Srinagar, Jammu & Kashmir',
    artisanRegion: 'Srinagar, Jammu & Kashmir',
    craftHeritage: 'GI-Tagged Kashmir Pashmina Handloom',
    category: 'Textiles & Weaving',
    shortDescription: 'Funding hand-spinning wheels (charkhas) and fine wooden looms to preserve authentic GI Pashmina weaving in Srinagar, Kashmir.',
    fullStory: "Authentic Pashmina is hand-spun from the soft undercoat of Ladakh Changthangi goats. This campaign provides traditional wooden spinning wheels to 35 elderly women spinners in rural Kashmir.",
    goalAmount: 350000,
    fundingGoal: 350000,
    pledgedAmount: 390000,
    amountRaised: 390000,
    backersCount: 290,
    daysLeft: 5,
    deadline: '2026-10-08',
    status: 'in_progress',
    isApproved: true,
    creatorProfilePhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    creatorBusinessName: 'Srinagar Pashmina Weavers Guild',
    creatorYearsOfExperience: 35,
    creatorCity: 'Srinagar',
    creatorState: 'Jammu & Kashmir',
    creatorLegalName: 'Ghulam Hassan',
    creatorPhone: '+91 94190 98765',
    imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80&sig=109',
    specs: [
      { label: 'Craft Origin', value: 'Srinagar, Kashmir (GI Tagged)' },
      { label: 'Fiber', value: '100% Raw Changthangi Pashmina Cashmere' },
    ],
    timeline: [
      { phase: 'Charkha Distribution', date: 'August 2026', description: 'Distributed 35 spinning wheels.' },
      { phase: 'Handloom Weaving', date: 'Nov 2026', description: 'Weaving patron stoles.' },
    ],
    rewardTiers: [
      {
        id: 'tier-09-a',
        title: 'Hand-Spin Pashmina Silk Blend Muffler',
        pledgeAmount: 2999,
        description: 'Ultra-soft hand-spun cashmere muffler with hand-twisted fringes.',
        estimatedDelivery: 'Nov 2026',
        itemsIncluded: ['1x Pashmina Muffler', 'Pashmina GI Mark Certificate'],
        backersCount: 85,
        maxBackers: 120,
      },
    ],
  },
];

export const MOCK_PRODUCTS: Product[] = [
  // 5 GRADUATED PRODUCTS (Plauisble outputs of campaigns)
  {
    id: 'prd-01',
    sku: 'CF-CHD-01',
    title: 'Handloom Chanderi Cotton-Silk Saree — Ivory & Gold Zari',
    creator: 'Radha Devi Handloom Collective',
    creatorLocation: 'Chanderi, Madhya Pradesh',
    artisanRegion: 'Chanderi, Madhya Pradesh',
    craftHeritage: 'GI-Tagged Chanderi Handloom Weaving',
    category: 'Textiles & Weaving',
    shortDescription: 'Regal ivory handloom cotton-silk saree woven on traditional pit-looms with pure tested silver-gold zari pallu.',
    longDescription: "Graduated from our successful pit-loom crowdfunding campaign on Craftify! Woven by Radha Devi's women artisan guild in Chanderi using hand-spun mulberry silk and organic cotton yarns. Features classic Ashrafi coin motives and gossamer lightness.",
    price: 3499,
    graduatedFromCampaignId: 'cmp-01',
    originalPledgedAmount: 315000,
    isFundedOnCraftify: true,
    isFundedOnLaunchMart: true,
    campaignBackersCount: 340,
    campaignGoalAmount: 250000,
    batchGraduated: 'Batch #01 • Summer 2026',
    rating: 4.9,
    reviewsCount: 42,
    inStock: true,
    stockCount: 15,
    badgeType: 'in_stock',
    badgeLabel: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80&sig=201',
    galleryImages: [
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80&sig=201',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80&sig=101',
    ],
    features: [
      '70% Fine Handspun Cotton & 30% Pure Mulberry Silk',
      'Tested Silver-Plated Zari Border & Pallu',
      'Includes 80cm unstitched blouse piece',
    ],
    specs: [
      { label: 'Length', value: '5.5m Saree + 0.8m Blouse' },
      { label: 'Provenance', value: 'Chanderi, Madhya Pradesh (GI Tagged)' },
    ],
    createdAt: '2026-08-15',
  },
  {
    id: 'prd-02',
    sku: 'CF-JPR-02',
    title: 'Jaipur Blue Pottery Ceramic Floral Table Vase',
    creator: 'Prajapati Blue Pottery Studio',
    creatorLocation: 'Jaipur, Rajasthan',
    artisanRegion: 'Jaipur, Rajasthan',
    craftHeritage: 'GI-Tagged Jaipur Blue Pottery',
    category: 'Pottery & Ceramics',
    shortDescription: 'Signature 10-inch cobalt blue glazed quartz ceramic vase hand-painted with traditional Persian marigold patterns.',
    longDescription: "Graduated from Rameshwar Prajapati's solar gas kiln campaign! Molded from quartz stone powder and multani mitti dough, then fired with lead-free mineral cobalt oxide glaze at 820°C.",
    price: 1899,
    graduatedFromCampaignId: 'cmp-02',
    originalPledgedAmount: 170000,
    isFundedOnCraftify: true,
    isFundedOnLaunchMart: true,
    campaignBackersCount: 195,
    campaignGoalAmount: 200000,
    batchGraduated: 'Batch #01 • Summer 2026',
    rating: 4.8,
    reviewsCount: 38,
    inStock: true,
    stockCount: 12,
    badgeType: 'in_stock',
    badgeLabel: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80&sig=202',
    galleryImages: [
      'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80&sig=202',
    ],
    features: [
      '100% Lead-Free & Cadmium-Free Glaze',
      'Hand-painted by master artisans in Kot Jewar',
      'Impervious to water absorption',
    ],
    specs: [
      { label: 'Height', value: '25 cm (10 inches)' },
      { label: 'Material', value: 'Quartz Powder & Glass Paste' },
    ],
    createdAt: '2026-08-20',
  },
  {
    id: 'prd-03',
    sku: 'CF-ASM-03',
    title: 'Handwoven Bamboo Table Lamp with Cane Shade',
    creator: 'Barpeta Bamboo & Cane Guild',
    creatorLocation: 'Barpeta, Assam',
    artisanRegion: 'Barpeta, Assam',
    craftHeritage: 'Assam Sustainable Bamboo Craft',
    category: 'Wood & Bamboo',
    shortDescription: 'Eco-friendly cylindrical desk lamp handcrafted from treated Bhaluka bamboo splints with warm ambient lighting.',
    longDescription: "Graduated from our Assam Bamboo Workshop campaign! Crafted from mature, borax-treated Assamese bamboo that is 100% beetle-proof. Fitted with brass E27 socket and braided jute electrical cable.",
    price: 1599,
    graduatedFromCampaignId: 'cmp-03',
    originalPledgedAmount: 385000,
    isFundedOnCraftify: true,
    isFundedOnLaunchMart: true,
    campaignBackersCount: 245,
    campaignGoalAmount: 320000,
    batchGraduated: 'Batch #01 • Summer 2026',
    rating: 4.9,
    reviewsCount: 56,
    inStock: true,
    stockCount: 20,
    badgeType: 'in_stock',
    badgeLabel: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80&sig=203',
    galleryImages: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80&sig=203',
    ],
    features: [
      'Non-toxic Borax treated termite-proof bamboo',
      'Includes 4W warm LED filament bulb',
      'Solid brass E27 socket holder',
    ],
    specs: [
      { label: 'Dimensions', value: '18cm Diameter × 40cm Height' },
      { label: 'Provenance', value: 'Barpeta, Assam' },
    ],
    createdAt: '2026-08-22',
  },
  {
    id: 'prd-04',
    sku: 'CF-TNJ-04',
    title: 'Hand-Cast Brass Kuthu Vilakku Temple Lamp (5-Wick)',
    creator: 'Swamimalai Chola Bronze Guild',
    creatorLocation: 'Swamimalai, Tamil Nadu',
    artisanRegion: 'Swamimalai, Tamil Nadu',
    craftHeritage: 'GI-Tagged Swamimalai Bronze & Brass Cast',
    category: 'Jewellery & Metalwork',
    shortDescription: 'Traditional 5-step handcrafted brass oil lamp cast using lost-wax technique with ornamental annam peacock finial.',
    longDescription: "Graduated from our Swamimalai Bronze Workshop Upgrade campaign! Cast in solid virgin brass by master sculptors. Features five hand-carved oil wick points crowned by a sacred Annam bird finial.",
    price: 2499,
    graduatedFromCampaignId: 'cmp-06',
    originalPledgedAmount: 240000,
    isFundedOnCraftify: true,
    isFundedOnLaunchMart: true,
    campaignBackersCount: 210,
    campaignGoalAmount: 280000,
    batchGraduated: 'Batch #01 • Summer 2026',
    rating: 4.9,
    reviewsCount: 64,
    inStock: true,
    stockCount: 14,
    badgeType: 'in_stock',
    badgeLabel: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1605885064070-5b5c92c46f17?auto=format&fit=crop&w=800&q=80&sig=204',
    galleryImages: [
      'https://images.unsplash.com/photo-1605885064070-5b5c92c46f17?auto=format&fit=crop&w=800&q=80&sig=204',
    ],
    features: [
      'Solid virgin brass with antique mirror gloss polish',
      '5 Wick capacity for traditional lighting',
      'Heavy pedestal base for balance',
    ],
    specs: [
      { label: 'Height', value: '42 cm • 1.8 kg Solid Brass' },
      { label: 'Provenance', value: 'Swamimalai, Tamil Nadu (GI Tagged)' },
    ],
    createdAt: '2026-08-25',
  },
  {
    id: 'prd-05',
    sku: 'CF-SHP-05',
    title: 'Saharanpur Hand-Carved Teakwood Jali Wall Panel',
    creator: 'Saharanpur Wooden Heritage Collective',
    creatorLocation: 'Saharanpur, Uttar Pradesh',
    artisanRegion: 'Saharanpur, Uttar Pradesh',
    craftHeritage: 'GI-Tagged Saharanpur Wood Craft',
    category: 'Woodcraft',
    shortDescription: 'Hand-chiselled solid seasoned teakwood geometric and floral jali lattice panel with natural walnut finish.',
    longDescription: "Graduated from our Saharanpur Solar Kiln Seasoning campaign! Hand-carved from solar-seasoned Sheesham and teakwood by master artisans using traditional iron gouges.",
    price: 1850,
    graduatedFromCampaignId: 'cmp-07',
    originalPledgedAmount: 195000,
    isFundedOnCraftify: true,
    isFundedOnLaunchMart: true,
    campaignBackersCount: 182,
    campaignGoalAmount: 220000,
    batchGraduated: 'Batch #01 • Summer 2026',
    rating: 5.0,
    reviewsCount: 76,
    inStock: true,
    stockCount: 15,
    badgeType: 'in_stock',
    badgeLabel: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80&sig=205',
    galleryImages: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80&sig=205',
    ],
    features: [
      'Solid kiln-seasoned teakwood',
      'Termite-resistant organic beeswax seal',
      'Pre-installed wall mounting brackets',
    ],
    specs: [
      { label: 'Dimensions', value: '45 cm × 45 cm × 2.5 cm' },
      { label: 'Provenance', value: 'Saharanpur, UP (GI Tagged)' },
    ],
    createdAt: '2026-08-28',
  },

  // 13 STANDARD MARKETPLACE PRODUCTS
  {
    id: 'prd-06',
    sku: 'CF-BAG-06',
    title: 'Hand Block-Printed Cotton Saree — Indigo Dabu Print',
    creator: 'Chhipa Block Print Guild',
    creatorLocation: 'Bagru, Rajasthan',
    artisanRegion: 'Bagru, Rajasthan',
    craftHeritage: 'GI-Tagged Bagru Dabu Mud-Resist Print',
    category: 'Textiles & Weaving',
    shortDescription: '100% Malmal cotton saree block-printed with mud-resist Dabu paste and dyed in natural indigo vats.',
    longDescription: "Hand-crafted in Bagru using hand-carved teakwood blocks. The mud resist paste (Dabu) is stamped onto unbleached cotton, sun-dried, dipped into deep indigo fermentation vats, and rinsed in river waters.",
    price: 2100,
    graduatedFromCampaignId: '',
    originalPledgedAmount: 0,
    isFundedOnCraftify: false,
    rating: 4.8,
    reviewsCount: 29,
    inStock: true,
    stockCount: 18,
    badgeType: 'in_stock',
    badgeLabel: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80&sig=206',
    galleryImages: [
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80&sig=206',
    ],
    features: ['100% Breathable Malmal Cotton', 'Natural Plant Indigo Dye', 'Unstitched Blouse Piece Included'],
    specs: [{ label: 'Length', value: '6.3m (with blouse)' }, { label: 'Provenance', value: 'Bagru, Rajasthan' }],
    createdAt: '2026-09-01',
  },
  {
    id: 'prd-07',
    sku: 'CF-KSH-07',
    title: 'Authentic Kashmiri Hand-Embroidered Pashmina Shawl',
    creator: 'Hassan Pashmina Artisans',
    creatorLocation: 'Srinagar, Jammu & Kashmir',
    artisanRegion: 'Srinagar, Jammu & Kashmir',
    craftHeritage: 'GI-Tagged Kashmir Sozni Embroidered Pashmina',
    category: 'Textiles & Weaving',
    shortDescription: 'Pure hand-spun Changthangi pashmina wool wrap adorned with delicate needle Sozni floral embroidery.',
    longDescription: "Crafted from 100% pure Ladakh goat cashmere, hand-spun on charkhas and woven on traditional wooden looms in Srinagar. Fine needle Sozni work frames the borders.",
    price: 7999,
    graduatedFromCampaignId: '',
    originalPledgedAmount: 0,
    isFundedOnCraftify: false,
    rating: 5.0,
    reviewsCount: 65,
    inStock: true,
    stockCount: 6,
    badgeType: 'limited_stock',
    badgeLabel: 'Limited Stock',
    imageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80&sig=207',
    galleryImages: [
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80&sig=207',
    ],
    features: ['100% Grade-A Changthangi Pashmina', 'Hand Sozni Needlework', 'Pashmina Mark Certified'],
    specs: [{ label: 'Dimensions', value: '200cm × 100cm' }, { label: 'Provenance', value: 'Srinagar, Kashmir' }],
    createdAt: '2026-08-30',
  },
  {
    id: 'prd-08',
    sku: 'CF-MTH-08',
    title: 'Madhubani Tree of Life Hand-Painted Canvas Wall Art',
    creator: 'Mithila Women Artists',
    creatorLocation: 'Madhubani, Bihar',
    artisanRegion: 'Madhubani, Bihar',
    craftHeritage: 'GI-Tagged Madhubani Painting',
    category: 'Folk & Tribal Art',
    shortDescription: 'Vibrant hand-painted Tree of Life canvas depicting birds and flora painted with natural botanical colors.',
    longDescription: "Hand-painted by Mithila women artists in Jitwarpur using fine bamboo nibs and natural mineral dyes extracted from indigo, turmeric, and madder root on primed cotton canvas.",
    price: 2899,
    graduatedFromCampaignId: '',
    originalPledgedAmount: 0,
    isFundedOnCraftify: false,
    rating: 4.9,
    reviewsCount: 19,
    inStock: true,
    stockCount: 10,
    badgeType: 'in_stock',
    badgeLabel: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80&sig=208',
    galleryImages: [
      'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80&sig=208',
    ],
    features: ['100% Hand-painted original art', 'Natural vegetable dyes', 'Stretched teak wood frame'],
    specs: [{ label: 'Size', value: '60cm × 45cm' }, { label: 'Provenance', value: 'Madhubani, Bihar' }],
    createdAt: '2026-09-03',
  },
  {
    id: 'prd-09',
    sku: 'CF-KLP-09',
    title: 'Traditional Kolhapuri Handcrafted Leather Sandals',
    creator: 'Kolhapur Cobblers Guild',
    creatorLocation: 'Kolhapur, Maharashtra',
    artisanRegion: 'Kolhapur, Maharashtra',
    craftHeritage: 'GI-Tagged Kolhapuri Leatherwork',
    category: 'Leather Craft',
    shortDescription: 'Supple vegetable-tanned buffalo leather open-toe sandals hand-stitched with waxed cotton thread.',
    longDescription: "Handcrafted in Kolhapur using natural babool-bark tanned leather. Breathable, durable, and naturally contours to the wearer's feet after a few hours of wear.",
    price: 1699,
    graduatedFromCampaignId: '',
    originalPledgedAmount: 0,
    isFundedOnCraftify: false,
    rating: 4.7,
    reviewsCount: 41,
    inStock: true,
    stockCount: 22,
    badgeType: 'in_stock',
    badgeLabel: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80&sig=209',
    galleryImages: [
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80&sig=209',
    ],
    features: ['100% Babool Bark Tanned Genuine Leather', 'Hand-stitched non-skid sole', 'Ergonomic footbed'],
    specs: [{ label: 'Sizes', value: 'IND 6, 7, 8, 9, 10, 11' }, { label: 'Provenance', value: 'Kolhapur, MH' }],
    createdAt: '2026-09-02',
  },
  {
    id: 'prd-10',
    sku: 'CF-VNS-10',
    title: 'Pure Banarasi Katan Silk Brocade Saree — Royal Crimson',
    creator: 'Master Weaver Haider Ali',
    creatorLocation: 'Varanasi, Uttar Pradesh',
    artisanRegion: 'Varanasi, Uttar Pradesh',
    craftHeritage: 'GI-Tagged Varanasi Katan Silk Handloom',
    category: 'Textiles & Weaving',
    shortDescription: 'Regal crimson red handloom silk saree featuring hand-woven tested gold zari floral kadhwa jaal.',
    longDescription: "Woven on traditional handlooms in Madanpura, Varanasi. Made from 100% pure mulberry Katan silk warp intertwined with golden tested zari threads over 20 days of weaving.",
    price: 5200,
    graduatedFromCampaignId: '',
    originalPledgedAmount: 0,
    isFundedOnCraftify: false,
    rating: 4.9,
    reviewsCount: 88,
    inStock: true,
    stockCount: 8,
    badgeType: 'in_stock',
    badgeLabel: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1610030469668-98e550d6193c?auto=format&fit=crop&w=800&q=80&sig=210',
    galleryImages: [
      'https://images.unsplash.com/photo-1610030469668-98e550d6193c?auto=format&fit=crop&w=800&q=80&sig=210',
    ],
    features: ['Pure Katan Silk with Silk Mark', 'Intricate kadhwa zari pallu', 'Unstitched blouse piece'],
    specs: [{ label: 'Length', value: '5.5m + 0.8m Blouse' }, { label: 'Provenance', value: 'Varanasi, UP' }],
    createdAt: '2026-08-29',
  },
  {
    id: 'prd-11',
    sku: 'CF-TER-11',
    title: 'Terracotta Handcrafted Clay Matka & Tea Kulhad Set',
    creator: 'Bankura Potters Collective',
    creatorLocation: 'Bankura, West Bengal',
    artisanRegion: 'Bankura, West Bengal',
    craftHeritage: 'Panchmura Terracotta Pottery',
    category: 'Pottery & Ceramics',
    shortDescription: 'Earthen clay festive set with 1.5L cooling water matka vessel and 4 fluted tea kulhads.',
    longDescription: "Crafted on manual potter flywheels using alluvial riverbed clay. Naturally microporous, it cools water via evaporation and imparts the traditional earthy mitti aroma.",
    price: 599,
    graduatedFromCampaignId: '',
    originalPledgedAmount: 0,
    isFundedOnCraftify: false,
    rating: 4.8,
    reviewsCount: 73,
    inStock: true,
    stockCount: 30,
    badgeType: 'in_stock',
    badgeLabel: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80&sig=211',
    galleryImages: [
      'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80&sig=211',
    ],
    features: ['100% Untreated natural clay', 'Naturally cooling water vessel', 'Lead-free & eco-friendly'],
    specs: [{ label: 'Set Contents', value: '1x Matka (1.5L) + 4x Cups' }, { label: 'Provenance', value: 'Bankura, WB' }],
    createdAt: '2026-09-04',
  },
  {
    id: 'prd-12',
    sku: 'CF-KND-12',
    title: 'Kondapalli Hand-Painted Wooden Toy Set — Village Musicians',
    creator: 'Kondapalli Toys Guild',
    creatorLocation: 'Kondapalli, Andhra Pradesh',
    artisanRegion: 'Kondapalli, Andhra Pradesh',
    craftHeritage: 'GI-Tagged Kondapalli Toys (Tella Poniki Wood)',
    category: 'Woodcraft',
    shortDescription: 'Set of 4 hand-carved lightweight wooden musician figurines painted with non-toxic lacquer colors.',
    longDescription: "Carved from softwood (Tella Poniki) found in Kondapalli hills. Each figure is hand-painted with vegetable dyes and shellac varnish depicting traditional folk performers.",
    price: 899,
    graduatedFromCampaignId: '',
    originalPledgedAmount: 0,
    isFundedOnCraftify: false,
    rating: 4.9,
    reviewsCount: 22,
    inStock: true,
    stockCount: 16,
    badgeType: 'in_stock',
    badgeLabel: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1558679908-541bcf1249ff?auto=format&fit=crop&w=800&q=80&sig=212',
    galleryImages: [
      'https://images.unsplash.com/photo-1558679908-541bcf1249ff?auto=format&fit=crop&w=800&q=80&sig=212',
    ],
    features: ['Lightweight Tella Poniki softwood', 'Non-toxic organic colors', 'Collectible Indian folk art'],
    specs: [{ label: 'Set', value: '4 Figures (12cm height)' }, { label: 'Provenance', value: 'Kondapalli, AP' }],
    createdAt: '2026-09-05',
  },
  {
    id: 'prd-13',
    sku: 'CF-BRS-13',
    title: 'Traditional Antique Brass Temple Bell Wall Chime',
    creator: 'Moradabad Metal Artisans',
    creatorLocation: 'Moradabad, Uttar Pradesh',
    artisanRegion: 'Moradabad, Uttar Pradesh',
    craftHeritage: 'Brassware of Moradabad',
    category: 'Jewellery & Metalwork',
    shortDescription: 'Tiered brass chain with 5 hand-cast resonant temple bells and ornamental brass chain.',
    longDescription: "Hand-cast in solid brass alloy by Moradabad metalsmiths. Produces a clear, long-sustaining resonant chime when struck by breeze or touch.",
    price: 1299,
    graduatedFromCampaignId: '',
    originalPledgedAmount: 0,
    isFundedOnCraftify: false,
    rating: 4.8,
    reviewsCount: 45,
    inStock: true,
    stockCount: 15,
    badgeType: 'in_stock',
    badgeLabel: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80&sig=213',
    galleryImages: [
      'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80&sig=213',
    ],
    features: ['Solid cast brass alloy', 'Resonant acoustic chime', 'Easy door/wall hook'],
    specs: [{ label: 'Length', value: '55 cm total length' }, { label: 'Provenance', value: 'Moradabad, UP' }],
    createdAt: '2026-09-01',
  },
  {
    id: 'prd-14',
    sku: 'CF-ZRD-14',
    title: 'Hand-Embroidered Zardozi Velvet Cushion Cover — Navy & Gold',
    creator: 'Lucknow Zardozi Collective',
    creatorLocation: 'Lucknow, Uttar Pradesh',
    artisanRegion: 'Lucknow, Uttar Pradesh',
    craftHeritage: 'GI-Tagged Lucknow Zardozi Embroidery',
    category: 'Textiles & Weaving',
    shortDescription: 'Plush midnight navy velvet cushion cover hand-embroidered with metallic gold dabka wires and pearls.',
    longDescription: "Created by women zardozi embroiderers in Lucknow. Metallic bullion wires (dabka) are couched over rich cotton velvet in traditional Awadhi royal floral patterns.",
    price: 799,
    graduatedFromCampaignId: '',
    originalPledgedAmount: 0,
    isFundedOnCraftify: false,
    rating: 4.9,
    reviewsCount: 52,
    inStock: true,
    stockCount: 25,
    badgeType: 'in_stock',
    badgeLabel: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80&sig=214',
    galleryImages: [
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80&sig=214',
    ],
    features: ['Plush Cotton Velvet Base', 'Hand-stitched metallic dabka work', 'Concealed zipper closure'],
    specs: [{ label: 'Size', value: '40cm × 40cm (16" × 16")' }, { label: 'Provenance', value: 'Lucknow, UP' }],
    createdAt: '2026-08-24',
  },
  {
    id: 'prd-15',
    sku: 'CF-JUT-15',
    title: 'Natural Jute & Cotton Hand-Braided Tote Bag',
    creator: 'Bengal Jute Artisans',
    creatorLocation: 'Kolkata, West Bengal',
    artisanRegion: 'Kolkata, West Bengal',
    craftHeritage: 'Eco-Friendly Jute Craft of Bengal',
    category: 'Bamboo & Cane',
    shortDescription: 'Sturdy eco-friendly shopper tote bag braided from natural golden jute fiber and cotton straps.',
    longDescription: "Hand-braided by jute artisan cooperatives in West Bengal. Lightweight, biodegradable, and reinforced with cotton lining and zipper pocket.",
    price: 699,
    graduatedFromCampaignId: '',
    originalPledgedAmount: 0,
    isFundedOnCraftify: false,
    rating: 4.7,
    reviewsCount: 31,
    inStock: true,
    stockCount: 40,
    badgeType: 'in_stock',
    badgeLabel: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=800&q=80&sig=215',
    galleryImages: [
      'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=800&q=80&sig=215',
    ],
    features: ['100% Golden Jute Fiber', 'Internal zippered pocket', 'Soft cotton padded handles'],
    specs: [{ label: 'Dimensions', value: '38cm × 35cm × 12cm' }, { label: 'Provenance', value: 'Kolkata, WB' }],
    createdAt: '2026-09-06',
  },
  {
    id: 'prd-16',
    sku: 'CF-JWL-16',
    title: 'Handcrafted Brass Temple Jewellery Set with Kemp Stones',
    creator: 'Swamimalai Jewellery Guild',
    creatorLocation: 'Swamimalai, Tamil Nadu',
    artisanRegion: 'Swamimalai, Tamil Nadu',
    craftHeritage: 'South Indian Temple Jewellery Craft',
    category: 'Jewellery & Metalwork',
    shortDescription: '22k gold-plated brass choker necklace set with ruby-red kemp stones and pearl droplet cluster.',
    longDescription: "Handcrafted using centuries-old temple jewellery techniques. Plated in high-luster gold with synthetic ruby kemp cabochons and freshwater pearl drops.",
    price: 2299,
    graduatedFromCampaignId: '',
    originalPledgedAmount: 0,
    isFundedOnCraftify: false,
    rating: 4.9,
    reviewsCount: 67,
    inStock: true,
    stockCount: 11,
    badgeType: 'in_stock',
    badgeLabel: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80&sig=216',
    galleryImages: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80&sig=216',
    ],
    features: ['22k Gold Micro-Plated Brass', 'Traditional Kemp Stone Inlay', 'Includes matching earrings'],
    specs: [{ label: 'Set', value: '1x Choker Necklace + 1x Pair Earrings' }, { label: 'Provenance', value: 'Tamil Nadu' }],
    createdAt: '2026-08-27',
  },
  {
    id: 'prd-17',
    sku: 'CF-WOD-17',
    title: 'Hand-Carved Walnut Wood Spice Box with Glass Inlay Lid',
    creator: 'Saharanpur Woodcarvers',
    creatorLocation: 'Saharanpur, Uttar Pradesh',
    artisanRegion: 'Saharanpur, Uttar Pradesh',
    craftHeritage: 'GI-Tagged Saharanpur Wood Craft',
    category: 'Woodcraft',
    shortDescription: 'Solid Sheesham wood kitchen organizer with 7 removable spice cups and hand-carved floral brass lid.',
    longDescription: "Kiln-seasoned Sheesham wood organizer carved by Saharanpur artisans. Features 7 interior compartments and brass wire Taarkashi inlay on the lid.",
    price: 1450,
    graduatedFromCampaignId: '',
    originalPledgedAmount: 0,
    isFundedOnCraftify: false,
    rating: 4.9,
    reviewsCount: 95,
    inStock: true,
    stockCount: 14,
    badgeType: 'in_stock',
    badgeLabel: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=800&q=80&sig=217',
    galleryImages: [
      'https://images.unsplash.com/photo-1607344645866-009c320c5ab8?auto=format&fit=crop&w=800&q=80&sig=217',
    ],
    features: ['Solid Sheesham Wood', '7 Removable cups + spoon', 'Brass Taarkashi wire inlay'],
    specs: [{ label: 'Size', value: '22cm Diameter × 7.5cm Height' }, { label: 'Provenance', value: 'Saharanpur, UP' }],
    createdAt: '2026-08-25',
  },
  {
    id: 'prd-18',
    sku: 'CF-KLM-18',
    title: 'Hand-Painted Kalamkari Silk Dupatta — Tree of Life',
    creator: 'Machilipatnam Kalamkari Artisans',
    creatorLocation: 'Machilipatnam, Andhra Pradesh',
    artisanRegion: 'Machilipatnam, Andhra Pradesh',
    craftHeritage: 'GI-Tagged Machilipatnam Kalamkari',
    category: 'Textiles & Weaving',
    shortDescription: 'Hand-drawn tussar silk dupatta depicting peacocks and floral vines painted with natural bamboo pen.',
    longDescription: "Hand-painted using bamboo styluses and botanical vegetable dyes on pure tussar silk in Pedana/Machilipatnam. Undergoes 17 natural dye and river-washing steps.",
    price: 2799,
    graduatedFromCampaignId: '',
    originalPledgedAmount: 0,
    isFundedOnCraftify: false,
    rating: 4.8,
    reviewsCount: 34,
    inStock: true,
    stockCount: 9,
    badgeType: 'in_stock',
    badgeLabel: 'In Stock',
    imageUrl: 'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=800&q=80&sig=218',
    galleryImages: [
      'https://images.unsplash.com/photo-1609357605129-26f69add5d6e?auto=format&fit=crop&w=800&q=80&sig=218',
    ],
    features: ['Pure Hand-spun Tussar Silk', 'Natural Vegetable Dyes', 'Hand-drawn Bamboo Pen Art'],
    specs: [{ label: 'Length', value: '2.5m × 0.9m' }, { label: 'Provenance', value: 'Pedana, AP' }],
    createdAt: '2026-09-03',
  },
];

export const MOCK_USER: User = INITIAL_USER;

export const MOCK_USER_PLEDGES: UserPledgeRecord[] = [
  {
    id: 'plg-01',
    campaignId: 'cmp-01',
    campaignTitle: 'Revive Chanderi Pit-Loom Weaving — New Looms & Natural Indigo Dye Setup',
    campaignCode: 'CMP-101',
    tierTitle: 'Pure Chanderi Cotton-Silk Scarf with Zari Border',
    amount: 2499,
    dateAuthorized: 'September 2, 2026',
    status: 'captured',
    estimatedDelivery: 'Nov 2026',
  },
  {
    id: 'plg-02',
    campaignId: 'cmp-02',
    campaignTitle: 'Jaipur Blue Pottery Studio Expansion & Lead-Free Solar Kiln',
    campaignCode: 'CMP-102',
    tierTitle: 'Set of 2 Cobalt Blue Glazed Decorative Platters',
    amount: 1499,
    dateAuthorized: 'September 8, 2026',
    status: 'authorized_pending',
    estimatedDelivery: 'Dec 2026',
  },
  {
    id: 'plg-03',
    campaignId: 'cmp-03',
    campaignTitle: 'Sustainable Assam Bhaluka Bamboo & Cane Workshop Setup',
    campaignCode: 'CMP-103',
    tierTitle: 'Woven Bamboo Desk Organizer & Pen Stand',
    amount: 799,
    dateAuthorized: 'August 28, 2026',
    status: 'captured',
    estimatedDelivery: 'Nov 2026',
  },
];

export const MOCK_CAMPAIGN_BACKERS: Record<string, BackerRecord[]> = {
  'cmp-01': [
    {
      id: 'bkr-101',
      campaignId: 'cmp-01',
      name: 'Aarav Sharma',
      amount: 2499,
      tierTitle: 'Pure Chanderi Cotton-Silk Scarf with Zari Border',
      date: '2 hours ago',
      status: 'authorized',
    },
    {
      id: 'bkr-102',
      campaignId: 'cmp-01',
      name: 'Priya Kulkarni',
      amount: 5800,
      tierTitle: 'Heirloom Chanderi Handloom Saree with Pure Zari Pallu',
      date: '4 hours ago',
      status: 'authorized',
    },
  ],
  'cmp-02': [
    {
      id: 'bkr-201',
      campaignId: 'cmp-02',
      name: 'Sunita Rao',
      amount: 1499,
      tierTitle: 'Set of 2 Cobalt Blue Glazed Decorative Platters',
      date: '1 hour ago',
      status: 'authorized',
    },
  ],
  'cmp-03': [
    {
      id: 'bkr-301',
      campaignId: 'cmp-03',
      name: 'Kavita Narayanan',
      amount: 799,
      tierTitle: 'Woven Bamboo Desk Organizer & Pen Stand',
      date: '3 hours ago',
      status: 'authorized',
    },
  ],
};

export const MOCK_CAMPAIGN_UPDATES: Record<string, CampaignUpdate[]> = {
  'cmp-01': [
    {
      id: 'upd-01-1',
      campaignId: 'cmp-01',
      title: 'First Teakwood Pit-Loom Frame Installed!',
      date: 'September 12, 2026',
      content: 'Thanks to your pledges, the carpenter master delivered our first heavy Burma teakwood frame. Warping 10,000 silk threads begins tomorrow!',
      author: 'Radha Devi',
    },
  ],
};

export const MOCK_CAMPAIGN_COMMENTS: Record<string, CampaignComment[]> = {
  'cmp-01': [
    {
      id: 'cmt-01-1',
      campaignId: 'cmp-01',
      author: 'Aarav Sharma',
      date: 'September 14, 2026',
      text: 'So proud to back traditional pit-loom weavers in Chanderi! Can’t wait for the indigo scarf.',
      avatarInitials: 'AS',
    },
  ],
};
`;

const srcDir = path.resolve('src');
fs.writeFileSync(path.join(srcDir, 'data/mockData.ts'), mockDataContent, 'utf-8');
console.log('Updated src/data/mockData.ts successfully');

const campaignsTsContent = `import { Campaign } from '../types';
import { MOCK_CAMPAIGNS } from '../data/mockData';

export const campaigns: Campaign[] = MOCK_CAMPAIGNS;
export default campaigns;
`;
fs.writeFileSync(path.join(srcDir, 'mockData/campaigns.ts'), campaignsTsContent, 'utf-8');
fs.writeFileSync(path.join(srcDir, 'data/campaigns.ts'), campaignsTsContent, 'utf-8');
console.log('Updated src/mockData/campaigns.ts and src/data/campaigns.ts');

const productsTsContent = `import { Product } from '../types';
import { MOCK_PRODUCTS } from '../data/mockData';

export const products: Product[] = MOCK_PRODUCTS;
export default products;
`;
fs.writeFileSync(path.join(srcDir, 'mockData/products.ts'), productsTsContent, 'utf-8');
console.log('Updated src/mockData/products.ts');
